repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        args: ['--profile', 'black']
        language: system
        types: [python]
